# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-11 19:27
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('networx', '0002_player_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='network_data',
        ),
        migrations.AddField(
            model_name='group',
            name='network_data',
            field=otree.db.models.LongStringField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='friends',
            field=otree.db.models.LongStringField(null=True),
        ),
    ]
