# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-11 19:41
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('networx', '0003_auto_20180611_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Melodee',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AddField(
            model_name='player',
            name='Roseanne',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AddField(
            model_name='player',
            name='Trudie',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
