a = {"elements": {"nodes": [
    {"data": {"id": "Roseanne", "name": "Roseanne"}, "position": {"x": 222, "y": 261}, "group": "nodes",
     "removed": false, "selected": false, "selectable": true, "locked": false, "grabbable": true, "classes": ""},
    {"data": {"id": "Trudie", "name": "Trudie"}, "position": {"x": 179, "y": 191}, "group": "nodes", "removed": false,
     "selected": false, "selectable": true, "locked": false, "grabbable": true, "classes": ""},
    {"data": {"id": "Melodee", "name": "Melodee"}, "position": {"x": 17, "y": 63}, "group": "nodes", "removed": false,
     "selected": false, "selectable": true, "locked": false, "grabbable": true, "classes": ""},
    {"data": {"id": "Sophie", "name": "Sophie"}, "position": {"x": 533, "y": 296}, "group": "nodes", "removed": false,
     "selected": false, "selectable": true, "locked": false, "grabbable": true, "classes": ""},
    {"data": {"id": "Nam", "name": "Nam"}, "position": {"x": 277, "y": 220}, "group": "nodes", "removed": false,
     "selected": false, "selectable": true, "locked": false, "grabbable": true, "classes": ""},
    {"data": {"id": "Keturah", "name": "Keturah"}, "position": {"x": 53, "y": 133}, "group": "nodes", "removed": false,
     "selected": false, "selectable": true, "locked": false, "grabbable": true, "classes": ""},
    {"data": {"id": "Etha", "name": "Etha"}, "position": {"x": 538, "y": 66}, "group": "nodes", "removed": false,
     "selected": false, "selectable": true, "locked": false, "grabbable": true, "classes": ""},
    {"data": {"id": "Ike", "name": "Ike"}, "position": {"x": 333, "y": 44}, "group": "nodes", "removed": false,
     "selected": false, "selectable": true, "locked": false, "grabbable": true, "classes": ""},
    {"data": {"id": "Piedad", "name": "Piedad"}, "position": {"x": 570, "y": 92}, "group": "nodes", "removed": false,
     "selected": false, "selectable": true, "locked": false, "grabbable": true, "classes": ""},
    {"data": {"id": "Nancy", "name": "Nancy"}, "position": {"x": 515, "y": 231}, "group": "nodes", "removed": false,
     "selected": false, "selectable": true, "locked": false, "grabbable": true, "classes": ""}], "edges": [{"data": {
    "source": "Trudie", "target": "Roseanne", "faveColor": "#86B342", "strength": 100, "id": "Trudie_Roseanne"},
                                                                                                            "position": {},
                                                                                                            "group": "edges",
                                                                                                            "removed": false,
                                                                                                            "selected": false,
                                                                                                            "selectable": true,
                                                                                                            "locked": false,
                                                                                                            "grabbable": true,
                                                                                                            "classes": ""},
                                                                                                           {"data": {
                                                                                                               "source": "Sophie",
                                                                                                               "target": "Roseanne",
                                                                                                               "faveColor": "#86B342",
                                                                                                               "strength": 100,
                                                                                                               "id": "Sophie_Roseanne"},
                                                                                                            "position": {},
                                                                                                            "group": "edges",
                                                                                                            "removed": false,
                                                                                                            "selected": false,
                                                                                                            "selectable": true,
                                                                                                            "locked": false,
                                                                                                            "grabbable": true,
                                                                                                            "classes": ""},
                                                                                                           {"data": {
                                                                                                               "source": "Melodee",
                                                                                                               "target": "Roseanne",
                                                                                                               "faveColor": "#86B342",
                                                                                                               "strength": 100,
                                                                                                               "id": "Melodee_Roseanne"},
                                                                                                            "position": {},
                                                                                                            "group": "edges",
                                                                                                            "removed": false,
                                                                                                            "selected": false,
                                                                                                            "selectable": true,
                                                                                                            "locked": false,
                                                                                                            "grabbable": true,
                                                                                                            "classes": ""}]},
     "style": [{"selector": "node", "style": {"label": "data(name)", "border-width": "3px", "border-color": "#333",
                                              "background-color": "#FAFAD2"}}, {"selector": "edge",
                                                                                "style": {"curve-style": "bezier",
                                                                                          "target-arrow-shape": "triangle",
                                                                                          "target-arrow-color": "#0000CD",
                                                                                          "line-color": "#87CEFA",
                                                                                          "width": "4px"}}],
     "zoomingEnabled": true, "userZoomingEnabled": false, "zoom": 0.9286898839137645, "minZoom": 1e-50,
     "maxZoom": 1e+50, "panningEnabled": true, "userPanningEnabled": true,
     "pan": {"x": 200.21558872305144, "y": -1.1442786069651731}, "boxSelectionEnabled": true,
     "renderer": {"name": "canvas"}}
